"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 07:20:00.303226
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_categories_name'), ['name'], unique=True)

    op.create_table('product_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_name'), ['name'], unique=True)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    op.create_table('shifts',
    sa.Column('name', sa.Enum('morning', 'evening', 'night', name='shiftname', native_enum=False, length=40), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'plant_manager', 'production_manager', 'quality_manager', 'maintenance_engineer', 'store_manager', 'production_supervisor', 'worker', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('materials',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('available_quantity', sa.Float(), nullable=False),
    sa.Column('minimum_stock_level', sa.Float(), nullable=False),
    sa.Column('reorder_level', sa.Float(), nullable=False),
    sa.Column('supplier_reference', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'discontinued', name='materialstatus', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['material_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_materials_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('low_stock', 'production_deadline', 'machine_breakdown', 'maintenance_due', 'critical_defect', 'high_rejection', 'production_delay', 'approval_pending', name='notificationtype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('plants',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'temporarily_closed', 'inactive', name='plantstatus', native_enum=False, length=40), nullable=False),
    sa.Column('production_capacity', sa.Float(), nullable=False),
    sa.Column('capacity_unit', sa.String(length=30), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_plants_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'discontinued', name='productstatus', native_enum=False, length=40), nullable=False),
    sa.Column('standard_production_time', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('boms',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_bom_product_version')
    )
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boms_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_boms_product_id'), ['product_id'], unique=False)

    op.create_table('production_lines',
    sa.Column('line_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('production_capacity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'inactive', name='linestatus', native_enum=False, length=40), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_lines_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_lines_line_code'), ['line_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_lines_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_lines_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_lines_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_lines_supervisor_id'), ['supervisor_id'], unique=False)

    op.create_table('bom_items',
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'material_id', name='uq_bom_item_material')
    )
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_items_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_items_material_id'), ['material_id'], unique=False)

    op.create_table('machines',
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('machine_type', sa.String(length=100), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('running', 'idle', 'maintenance', 'breakdown', 'decommissioned', name='machinestatus', native_enum=False, length=40), nullable=False),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_due', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_machine_code'), ['machine_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_machines_machine_type'), ['machine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_next_maintenance_due'), ['next_maintenance_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_status'), ['status'], unique=False)

    op.create_table('production_orders',
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='orderpriority', native_enum=False, length=40), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'in_progress', 'paused', 'completed', 'cancelled', name='orderstatus', native_enum=False, length=40), nullable=False),
    sa.Column('approval_stage', sa.Enum('created', 'supervisor_reviewed', 'material_checked', 'production_started', 'quality_inspected', 'production_completed', 'manager_approved', name='approvalstage', native_enum=False, length=40), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_orders_approval_stage'), ['approval_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_orders_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_orders_target_date'), ['target_date'], unique=False)

    op.create_table('workers',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'on_leave', 'inactive', name='workerstatus', native_enum=False, length=40), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_skill'), ['skill'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_user_id'), ['user_id'], unique=False)

    op.create_table('approval_logs',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('created', 'supervisor_reviewed', 'material_checked', 'production_started', 'quality_inspected', 'production_completed', 'manager_approved', name='approvalstage', native_enum=False, length=40), nullable=True),
    sa.Column('to_stage', sa.Enum('created', 'supervisor_reviewed', 'material_checked', 'production_started', 'quality_inspected', 'production_completed', 'manager_approved', name='approvalstage', native_enum=False, length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_logs_order_id'), ['order_id'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('preventive', 'breakdown', name='maintenancetype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='maintenancestatus', native_enum=False, length=40), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_maintenance_type'), ['maintenance_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_technician_id'), ['technician_id'], unique=False)

    op.create_table('production_batches',
    sa.Column('batch_number', sa.String(length=60), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='batchstatus', native_enum=False, length=40), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_batches_batch_number'), ['batch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_batches_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_batches_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_batches_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_batches_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_batches_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_batches_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_batches_status'), ['status'], unique=False)

    op.create_table('batch_workers',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'worker_id', name='uq_batch_worker')
    )
    with op.batch_alter_table('batch_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_workers_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_workers_worker_id'), ['worker_id'], unique=False)

    op.create_table('downtimes',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('machine_breakdown', 'material_shortage', 'quality_issue', 'power_failure', 'maintenance', 'operator_issue', name='downtimecategory', native_enum=False, length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_records.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downtimes', schema=None) as batch_op:
        batch_op.create_index('ix_downtime_machine_start', ['machine_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_downtimes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_downtimes_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downtimes_machine_id'), ['machine_id'], unique=False)

    op.create_table('inspections',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.Enum('incoming_material', 'in_process', 'final_product', name='inspectiontype', native_enum=False, length=40), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Enum('pass', 'fail', name='inspectionresult', native_enum=False, length=40), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspection_date'), ['inspection_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspection_type'), ['inspection_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_result'), ['result'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('movement_type', sa.Enum('receipt', 'consumption', 'stock_out', 'finished_goods', 'rejected_goods', 'adjustment', name='movementtype', native_enum=False, length=40), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_inv_material_created', ['material_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_product_id'), ['product_id'], unique=False)

    op.create_table('production_output_logs',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('produced', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_output_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_output_logs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_output_logs_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_output_logs_shift_id'), ['shift_id'], unique=False)

    op.create_table('spare_part_usages',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=150), nullable=False),
    sa.Column('part_number', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_usages_maintenance_id'), ['maintenance_id'], unique=False)

    op.create_table('defects',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('quantity_affected', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='resolutionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_defect_type'), ['defect_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_resolution_status'), ['resolution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_severity'), ['severity'], unique=False)

    op.create_table('inspection_parameters',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('expected_value', sa.String(length=100), nullable=False),
    sa.Column('actual_value', sa.String(length=100), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_parameters_inspection_id'), ['inspection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_parameters_inspection_id'))

    op.drop_table('inspection_parameters')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_severity'))
        batch_op.drop_index(batch_op.f('ix_defects_resolution_status'))
        batch_op.drop_index(batch_op.f('ix_defects_product_id'))
        batch_op.drop_index(batch_op.f('ix_defects_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_defects_defect_type'))
        batch_op.drop_index(batch_op.f('ix_defects_batch_id'))

    op.drop_table('defects')
    with op.batch_alter_table('spare_part_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_usages_maintenance_id'))

    op.drop_table('spare_part_usages')
    with op.batch_alter_table('production_output_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_output_logs_shift_id'))
        batch_op.drop_index(batch_op.f('ix_production_output_logs_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_production_output_logs_batch_id'))

    op.drop_table('production_output_logs')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_material_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_batch_id'))
        batch_op.drop_index('ix_inv_material_created')

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_result'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspection_type'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspection_date'))
        batch_op.drop_index(batch_op.f('ix_inspections_batch_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('downtimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downtimes_machine_id'))
        batch_op.drop_index(batch_op.f('ix_downtimes_line_id'))
        batch_op.drop_index(batch_op.f('ix_downtimes_category'))
        batch_op.drop_index('ix_downtime_machine_start')

    op.drop_table('downtimes')
    with op.batch_alter_table('batch_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_workers_worker_id'))
        batch_op.drop_index(batch_op.f('ix_batch_workers_batch_id'))

    op.drop_table('batch_workers')
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_batches_status'))
        batch_op.drop_index(batch_op.f('ix_production_batches_start_time'))
        batch_op.drop_index(batch_op.f('ix_production_batches_shift_id'))
        batch_op.drop_index(batch_op.f('ix_production_batches_order_id'))
        batch_op.drop_index(batch_op.f('ix_production_batches_machine_id'))
        batch_op.drop_index(batch_op.f('ix_production_batches_line_id'))
        batch_op.drop_index(batch_op.f('ix_production_batches_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_production_batches_batch_number'))

    op.drop_table('production_batches')
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_technician_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_maintenance_type'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_machine_id'))

    op.drop_table('maintenance_records')
    with op.batch_alter_table('approval_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_logs_order_id'))

    op.drop_table('approval_logs')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_user_id'))
        batch_op.drop_index(batch_op.f('ix_workers_status'))
        batch_op.drop_index(batch_op.f('ix_workers_skill'))
        batch_op.drop_index(batch_op.f('ix_workers_shift_id'))
        batch_op.drop_index(batch_op.f('ix_workers_line_id'))
        batch_op.drop_index(batch_op.f('ix_workers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_workers_full_name'))
        batch_op.drop_index(batch_op.f('ix_workers_employee_code'))
        batch_op.drop_index(batch_op.f('ix_workers_department'))

    op.drop_table('workers')
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_orders_target_date'))
        batch_op.drop_index(batch_op.f('ix_production_orders_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_production_orders_status'))
        batch_op.drop_index(batch_op.f('ix_production_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_production_orders_priority'))
        batch_op.drop_index(batch_op.f('ix_production_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_production_orders_line_id'))
        batch_op.drop_index(batch_op.f('ix_production_orders_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_production_orders_approval_stage'))

    op.drop_table('production_orders')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_status'))
        batch_op.drop_index(batch_op.f('ix_machines_next_maintenance_due'))
        batch_op.drop_index(batch_op.f('ix_machines_name'))
        batch_op.drop_index(batch_op.f('ix_machines_machine_type'))
        batch_op.drop_index(batch_op.f('ix_machines_machine_code'))
        batch_op.drop_index(batch_op.f('ix_machines_line_id'))
        batch_op.drop_index(batch_op.f('ix_machines_is_deleted'))

    op.drop_table('machines')
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_items_material_id'))
        batch_op.drop_index(batch_op.f('ix_bom_items_bom_id'))

    op.drop_table('bom_items')
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_lines_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_production_lines_status'))
        batch_op.drop_index(batch_op.f('ix_production_lines_plant_id'))
        batch_op.drop_index(batch_op.f('ix_production_lines_name'))
        batch_op.drop_index(batch_op.f('ix_production_lines_line_code'))
        batch_op.drop_index(batch_op.f('ix_production_lines_is_deleted'))

    op.drop_table('production_lines')
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boms_product_id'))
        batch_op.drop_index(batch_op.f('ix_boms_is_active'))

    op.drop_table('boms')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_status'))
        batch_op.drop_index(batch_op.f('ix_plants_name'))
        batch_op.drop_index(batch_op.f('ix_plants_manager_id'))
        batch_op.drop_index(batch_op.f('ix_plants_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_plants_code'))
        batch_op.drop_index(batch_op.f('ix_plants_city'))

    op.drop_table('plants')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_dedupe_key'))
        batch_op.drop_index('ix_notif_user_read')

    op.drop_table('notifications')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_status'))
        batch_op.drop_index(batch_op.f('ix_materials_name'))
        batch_op.drop_index(batch_op.f('ix_materials_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_materials_code'))
        batch_op.drop_index(batch_op.f('ix_materials_category_id'))

    op.drop_table('materials')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('shifts')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_name'))

    op.drop_table('product_categories')
    with op.batch_alter_table('material_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_categories_name'))

    op.drop_table('material_categories')
    # ### end Alembic commands ###
